### ISSUE TITLE
Download does not complete - stuck at 94%

### ISSUE THREAD

**Issue by MikMuz** [NUMde/compass-num-conformance-checker#7]
Dear Team,

we tried to execute following command "./gradlew clean compass-conformance-server:bootRun -Dspring.profile.active=h2" on a mac. Attached you can see the Terminal screenshot.

<img width="1274" alt="Screenshot 2021-09-22 at 09 37 40" src="https://user-images.githubusercontent.com/75631527/134302274-dee90924-9127-4329-ab5c-2c0b1a1a55d6.png">

Could you help us here?
Kind Regards

**Comment by JohannesOehm** [comment]
Can you try if the server is running anyway? To me it looks like the server is running.

I guess the progress indicator (which is not an indicator of download process, but of build process) is stuck there because the bootRun-Task will not be completed until the process is shut down.

**Comment by MikMuz** [comment]
Hey 
Thanks for your response. 

We tried to see if the server is working for us, however, we receive the Whitelabel Error Page. Are we overseeing something?

<img width="1001" alt="Screenshot 2021-09-22 at 15 59 49" src="https://user-images.githubusercontent.com/75631527/134359240-aa8c5356-6f9d-48d5-9cae-85ed7d900c59.png">

How could I shut down the process, if it is not complete yet? Would I not loose what has already been built?

**Comment by JohannesOehm** [comment]
Thats totally normal, the server is up and running. Do you see a page when you just visit http://localhost:8080/ ?

You can stop it with <kbd>Ctrl</kbd>+<kbd>C</kbd> (maybe it's <kbd>Cmd</kbd>+<kbd>C</kbd> on Mac OS, I don't know).

No, you won't loose anything, but using the default configuration, the server reads the entire SNOMED and LOINC codes into an in-memory H2 database, that process would start again if you restart the server.

**Comment by MikMuz** [comment]
Hey

thank you for sharing http://localhost:8080/ .
I was able to successfully access the server whilst the terminal was still running.

I do not have any resources to validate, so I used the resources found on https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Patient-duplicate-2

When using the conformity checker I receive several error messages
<img width="1355" alt="Screenshot 2021-09-23 at 11 00 26" src="https://user-images.githubusercontent.com/75631527/134480488-290ed700-bb28-40b4-a0c2-611cbd196fbf.png">


However, when using the simplifier validator https://simplifier.net/validate
I get no issues.
<img width="1214" alt="Screenshot 2021-09-23 at 11 01 36" src="https://user-images.githubusercontent.com/75631527/134480580-c03ad5f0-1018-4584-8778-4abed49fd4b5.png">

Could you possibly share a conformed resource in order to successfully test the conformity checker?

**Comment by JohannesOehm** [comment]
Can you create a seperate issue for this?
