### ISSUE TITLE
Error Messages in Conformity checker - no Error on Simplifier validator

### ISSUE THREAD

**Issue by MikMuz** [NUMde/compass-num-conformance-checker#8]
Hey

thank you for sharing http://localhost:8080/ .
I was able to successfully access the server whilst the terminal was still running.

I do not have any resources to validate, so I used the resources found on https://simplifier.net/guide/GermanCoronaConsensusDataSet-ImplementationGuide/Patient-duplicate-2

When using the conformity checker I receive several error messages
<img width="1355" alt="Screenshot 2021-09-23 at 11 00 26" src="https://user-images.githubusercontent.com/75631527/134480488-290ed700-bb28-40b4-a0c2-611cbd196fbf.png">

However, when using the simplifier validator https://simplifier.net/validate
I get no issues.
<img width="1214" alt="Screenshot 2021-09-23 at 11 01 36" src="https://user-images.githubusercontent.com/75631527/134480580-c03ad5f0-1018-4584-8778-4abed49fd4b5.png">

Could you possibly share a conformed resource in order to successfully test the conformity checker?

_Originally posted by @MikMuz in https://github.com/NUMde/compass-num-conformance-checker/issues/7#issuecomment-925628475_

**Comment by JohannesOehm** [comment]
This is a simple example that should work.

[dd06747c-03df-4adb-9dbb-90b38dccab16-5cad9d8a-fa19-43d5-9d06-275cd2b9858a-gecco-bundle.txt](https://github.com/NUMde/compass-num-conformance-checker/files/7217178/dd06747c-03df-4adb-9dbb-90b38dccab16-5cad9d8a-fa19-43d5-9d06-275cd2b9858a-gecco-bundle.txt)


Maybe you could post the Patient resource here you used to test the validator, so that people from D4L can try to reproduce the error.

**Comment by MikMuz** [comment]
Hey

please find the Patient Resource that we tested successfully on the simplifier validator, however, unsuccessfully via the Conformity Checker 

{
    "resourceType": "Patient",
    "id": "patient-num-codex-example",
    "meta": {

    },
    
    "extension":  [
        {
            "url": "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/ethnic-group",
            "valueCoding": {
                "system": "http://snomed.info/sct",
                "code": "26242008",
                "display": "Mixed (qualifier value)"
            }
        },
        {
            "url": "https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/age",
            "extension":  [
                {
                    "url": "dateTimeOfDocumentation",
                    "valueDateTime": "2020-10-01"
                },
                {
                    "url": "age",
                    "valueAge": {
                        "value": 67,
                        "unit": "years",
                        "system": "http://unitsofmeasure.org",
                        "code": "a"
                    }
                }
            ]
        }
    ],
    "identifier":  [
        {
            "type": {
                "coding":  [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "ANON"
                    }
                ]
            },
            "system": "http://www.netzwerk-universitaetsmedizin.de/sid/crr-pseudonym",
            "value": "codex_6348Q7"
        }
    ],
    "birthDate": "1953-09-30"
}




Unfortunately when trying to validate the "Gecco-Bundle.txt" from your previous message, a few messages appear, as can be seen here. 

<img width="1194" alt="Screenshot 2021-09-23 at 14 56 05" src="https://user-images.githubusercontent.com/75631527/134510542-3cff64b9-a580-456d-87d6-f102028b3660.png">
 

Am I overseeing something here potentially?

**Comment by JohannesOehm** [comment]
Can you remove the "meta": {} part. If I had to guess, FHIR does not allow empty objects and therefore the error is thrown...

Only red boxes indicate errors, the others are only warnings you can ignore.

**Comment by MikMuz** [comment]
Hey

thanks for the advice with leaving out the "meta": {} part. We only got 2 messages, none being an error message.


<img width="1180" alt="Screenshot 2021-09-24 at 14 28 36" src="https://user-images.githubusercontent.com/75631527/134674253-5f98a175-45a8-4216-b275-8c54fc46faf1.png">

How do I know if the validation became a success? As long as I do not see any red error messages?

**Comment by JohannesOehm** [comment]
Yes, if there are no red error messages, the validation was successful.

**Comment by MikMuz** [comment]
Thank you for clarifying.
